[package]
name = "cuna"
version = "0.1.0"
authors = ["snylonue <snylonue@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5"
anyhow = "1"
thiserror = "1"